# Generated by Django 6.0.2 on 2026-02-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_community_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_cards/'),
        ),
    ]
