# Generated by Django 6.0.2 on 2026-02-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_profile_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster_image',
            field=models.FileField(blank=True, null=True, upload_to='event_posters/'),
        ),
        migrations.AddField(
            model_name='post',
            name='poster_image',
            field=models.FileField(blank=True, null=True, upload_to='post_posters/'),
        ),
    ]
