# Generated by Django 6.0.2 on 2026-02-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_event_poster_image_post_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
