# Generated by Django 6.0.2 on 2026-03-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_community_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
