# Generated by Django 6.0.2 on 2026-03-01 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_profile_department_profile_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty_verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
